INSERT INTO enfermidade (descricao) VALUES

('CANCER'),
('CANCER AMIGDALA'),
('CANCER AXILA'),
('CANCER BEXIGA'),
('CANCER BOCA'),
('CANCER BRACO'),
('CANCER CEREBRO'),
('CANCER COLO UTERO'),
('CANCER COLUNA'),
('CANCER DUCTAL INFILTRANTE'),
('CANCER ESOFAGO'),
('CANCER ESTOMAGO'),
('CANCER FIGADO'),
('CANCER GARGANTA'),
('CANCER INGINAL'),
('CANCER INTESTINO'),
('CANCER MAMA'),
('CANCER MEDIASTINO'),
('CANCER MEDULA'),
('CANCER NARIZ'),
('CANCER OLHO'),
('CANCER OSSOS'),
('CANCER OVARIO'),
('CANCER PANCREAS'),
('CANCER PANTURRILHA'),
('CANCER PELE'),
('CANCER PELVICO'),
('CANCER PENIS'),
('CANCER PESCOCO'),
('CANCER PROSTATA'),
('CANCER PULMAO'),
('CANCER RETO'),
('CANCER RINS'),
('CANCER TESTICULO'),
('CANCER TIREOIDE'),
('CANCER TORAX'),
('CANCER UTERO'),
('CANCER VAGINA'),
('CANCER VESICULA'),
('CANCER VIRILHA'),
('CANCER VULVA'),
('CARCINOMA'),
('CARCINOMA COLO UTERO'),
('CARCINOMA DUCTAL'),
('CARCINOMA ESCAMOCELULAR'),
('CARCINOMA INVASOR'),
('CARCINOMA TIREOIDE'),
('ESTENOSE ESOFAGO'),
('HIPERPLASIA LINFOIDE'),
('HIPOFARINGE'),
('LEUCEMIA'),
('LEUCEMIA AGUDA'),
('LEUCEMIA MIELOIDE CRONICA'),
('LINFOMA'),
('LINFOMA GASTRICO'),
('LINFONODO CERVICAL'),
('METASTASE'),
('METASTASE CEREBRAL'),
('MICOSE FUNGOIDE'),
('MIELOMA MULTIPLO'),
('NEOPLASIA COLON'),
('NEOPLASIA GATRICA'),
('NEOPLASIA OVARIO'),
('NEOPLASIA PELE'),
('NODULO COXA'),
('NODULO PESCOCO'),
('TUMOR'),
('TUMOR ABDOMINAL'),
('TUMOR CEREBRO'),
('TUMOR COXA'),
('TUMOR OVARIO'),
('TUMOR PAREDE TORAXICA'),
('TUMOR PARTES MOLES'),
('TUMOR PERNA'),
('TUMOR PLACENTA'),
('TUMOR RETO'),
('TUMOR RETROPERITONEAL'),
('TUMOR RINS');

INSERT INTO enfermidade (cid, descricao)
VALUES

('C00', 'Neoplasia maligna do lábio'),
('C01', 'Neoplasia maligna da base da língua'),
('C02', 'Neoplasia maligna de outras partes e de partes não especificadas da língua'),
('C03', 'Neoplasia maligna da gengiva'),
('C04', 'Neoplasia maligna do assoalho da boca'),
('C05', 'Neoplasia maligna do palato'),
('C06', 'Neoplasia maligna de outras partes e de partes não especificadas da boca'),
('C07', 'Neoplasia maligna da glândula parótida'),
('C08', 'Neoplasia maligna de outras glândulas salivares maiores e as não especificadas'),
('C09', 'Neoplasia maligna da amígdala'),
('C10', 'Neoplasia maligna da orofaringe'),
('C11', 'Neoplasia maligna da nasofaringe'),
('C12', 'Neoplasia maligna do seio piriforme'),
('C13', 'Neoplasia maligna da hipofaringe'),
('C14', 'Neoplasia maligna de outras localizações e de localizações mal definida, do lábio, cavidade oral e faringe'),
('C15', 'Neoplasia maligna do esôfago'),
('C16', 'Neoplasia maligna do estômago'),
('C17', 'Neoplasia maligna do intestino delgado'),
('C18', 'Neoplasia maligna do cólon'),
('C19', 'Neoplasia maligna da junção retossigmóide'),
('C20', 'Neoplasia maligna do reto'),
('C21', 'Neoplasia maligna do ânus e do canal anal'),
('C22', 'Neoplasia maligna do fígado e das vias biliares intra-hepáticas'),
('C23', 'Neoplasia maligna da vesícula biliar'),
('C24', 'Neoplasia maligna de outras partes, e de partes não especificadas das vias biliares'),
('C25', 'Neoplasia maligna do pâncreas'),
('C26', 'Neoplasia maligna de outros órgãos digestivos e de localizações mal definidas no aparelho digestivo'),
('C30', 'Neoplasia maligna da cavidade nasal e do ouvido médio'),
('C31', 'Neoplasia maligna dos seios da face'),
('C32', 'Neoplasia maligna da laringe'),
('C33', 'Neoplasia maligna da traquéia'),
('C34', 'Neoplasia maligna dos brônquios e dos pulmões'),
('C37', 'Neoplasia maligna do timo'),
('C38', 'Neoplasia maligna do coração, mediastino e pleura'),
('C39', 'Neoplasia maligna de outras localizações e de localizações mal definidas do aparelho respiratório e dos órgãos intratorácicos'),
('C40', 'Neoplasia maligna dos ossos e cartilagens articulares dos membros'),
('C41', 'Neoplasia maligna dos ossos e das cartilagens articulares de outras localizações e de localizações não especificadas'),
('C43', 'Melanoma maligno da pele'),
('C44', 'Outras neoplasias malignas da pele'),
('C45', 'Mesotelioma'),
('C46', 'Sarcoma de Kaposi'),
('C47', 'Neoplasia maligna dos nervos periféricos e do sistema nervoso autônomo'),
('C48', 'Neoplasia maligna dos tecidos moles do retroperitônio e do peritônio'),
('C49', 'Neoplasia maligna do tecido conjuntivo e de outros tecidos moles'),
('C50', 'Neoplasia maligna da mama'),
('C51', 'Neoplasia maligna da vulva'),
('C52', 'Neoplasia maligna da vagina'),
('C53', 'Neoplasia maligna do colo do útero'),
('C54', 'Neoplasia maligna do corpo do útero'),
('C55', 'Neoplasia maligna do útero, porção não especificada'),
('C56', 'Neoplasia maligna do ovário'),
('C57', 'Neoplasia maligna de outros órgãos genitais femininos e dos não especificados'),
('C58', 'Neoplasia maligna da placenta'),
('C60', 'Neoplasia maligna do pênis'),
('C61', 'Neoplasia maligna da próstata'),
('C62', 'Neoplasia maligna dos testículos'),
('C63', 'Neoplasia maligna de outros órgãos genitais masculinos e dos não especificados'),
('C64', 'Neoplasia maligna do rim, exceto pelve renal'),
('C65', 'Neoplasia maligna da pelve renal'),
('C66', 'Neoplasia maligna dos ureteres'),
('C67', 'Neoplasia maligna da bexiga'),
('C68', 'Neoplasia maligna de outros órgãos urinários e dos não especificados'),
('C69', 'Neoplasia maligna do olho e anexos'),
('C70', 'Neoplasia maligna das meninges'),
('C71', 'Neoplasia maligna do encéfalo'),
('C72', 'Neoplasia maligna da medula espinhal, dos nervos cranianos e de outras partes do sistema nervoso central'),
('C73', 'Neoplasia maligna da glândula tireóide'),
('C74', 'Neoplasia maligna da glândula supra-renal [Glândula adrenal]'),
('C75', 'Neoplasia maligna de outras glândulas endócrinas e de estruturas relacionadas'),
('C76', 'Neoplasia maligna de outras localizações e de localizações mal definidas'),
('C77', 'Neoplasia maligna secundária e não especificada dos gânglios linfáticos'),
('C78', 'Neoplasia maligna secundária dos órgãos respiratórios e digestivos'),
('C79', 'Neoplasia maligna secundária de outras localizações'),
('C80', 'Neoplasia maligna, sem especificação de localização'),
('C81', 'Doença de Hodgkin'),
('C82', 'Linfoma não-Hodgkin, folicular (nodular)'),
('C83', 'Linfoma não-Hodgkin difuso'),
('C84', 'Linfomas de células T cutâneas e periféricas'),
('C85', 'Linfoma não-Hodgkin de outros tipos e de tipo não especificado'),
('C88', 'Doenças imunoproliferativas malignas'),
('C90', 'Mieloma múltiplo e neoplasias malignas de plasmócitos'),
('C91', 'Leucemia linfóide'),
('C92', 'Leucemia mielóide'),
('C93', 'Leucemia monocítica'),
('C94', 'Outras leucemias de células de tipo especificado'),
('C95', 'Leucemia de tipo celular não especificado'),
('C96', 'Outras neoplasias malignas e as não especificadas dos tecidos linfático, hematopoético e tecidos correlatos'),
('C97', 'Neoplasias malignas de localizações múltiplas independentes (primárias)'),
('D00', 'Carcinoma in situ da cavidade oral, do esôfago e do estômago'),
('D01', 'Carcinoma in situ de outros órgãos digestivos'),
('D02', 'Carcinoma in situ do ouvido médio e do aparelho respiratório'),
('D03', 'Melanoma in situ'),
('D04', 'Carcinoma in situ da pele'),
('D05', 'Carcinoma in situ da mama'),
('D06', 'Carcinoma in situ do colo do útero (cérvix)'),
('D07', 'Carcinoma in situ de outros órgãos genitais e dos não especificados'),
('D09', 'Carcinoma in situ de outras localizações e das não especificadas'),
('D10', 'Neoplasia benigna da boca e da faringe'),
('D11', 'Neoplasia benigna de glândulas salivares maiores'),
('D12', 'Neoplasia benigna do cólon, reto, canal anal e ânus'),
('D13', 'Neoplasia benigna de outras partes e de partes mal definidas do aparelho digestivo'),
('D14', 'Neoplasia benigna do ouvido médio e do aparelho respiratório'),
('D15', 'Neoplasia benigna de outros órgãos intratorácicos e dos não especificados'),
('D16', 'Neoplasia benigna de osso e de cartilagem articular'),
('D17', 'Neoplasia lipomatosa benigna'),
('D18', 'Hemangioma e linfangioma de qualquer localização'),
('D19', 'Neoplasia benigna de tecido mesotelial'),
('D20', 'Neoplasia benigna de tecido mole do retroperitônio e do peritônio'),
('D21', 'Outras neoplasias benignas do tecido conjuntivo e de outros tecidos moles'),
('D22', 'Nevos melanocíticos'),
('D23', 'Outras neoplasias benignas da pele'),
('D24', 'Neoplasia benigna da mama'),
('D25', 'Leiomioma do útero'),
('D26', 'Outras neoplasias benignas do útero'),
('D27', 'Neoplasia benigna do ovário'),
('D28', 'Neoplasia benigna de outros órgãos genitais femininos e de órgãos não especificados'),
('D29', 'Neoplasia benigna dos órgãos genitais masculinos'),
('D30', 'Neoplasia benigna dos órgãos urinários'),
('D31', 'Neoplasia benigna do olho e anexos'),
('D32', 'Neoplasia benigna das meninges'),
('D33', 'Neoplasia benigna do encéfalo e de outras partes do sistema nervoso central'),
('D34', 'Neoplasia benigna da glândula tireóide'),
('D35', 'Neoplasia benigna de outras glândulas endócrinas e das não especificadas'),
('D36', 'Neoplasia benigna de outras localizações e de localizações não especificadas'),
('D37', 'Neoplasia de comportamento incerto ou desconhecido da cavidade oral e dos órgãos digestivos'),
('D38', 'Neoplasia de comportamento incerto ou desconhecido do ouvido médio e dos órgãos respiratórios e intratorácicos'),
('D39', 'Neoplasia de comportamento incerto ou desconhecido dos órgãos genitais femininos'),
('D40', 'Neoplasia de comportamento incerto ou desconhecido dos órgãos genitais masculinos'),
('D41', 'Neoplasia de comportamento incerto ou desconhecido dos órgãos urinários'),
('D42', 'Neoplasia de comportamento incerto ou desconhecido das meninges'),
('D43', 'Neoplasia de comportamento incerto ou desconhecido do encéfalo e do sistema nervoso central'),
('D44', 'Neoplasia de comportamento incerto ou desconhecido das glândulas endócrinas'),
('D45', 'Policitemia vera'),
('D46', 'Síndromes mielodisplásicas'),
('D47', 'Outras neoplasias de comportamento incerto ou desconhecido dos tecidos linfático, hematopoético e tecidos correlatos'),
('D48', 'Neoplasia de comportamento incerto ou desconhecido de outras localizações e de localizações não especificadas');

